name: AWS Credentials Test and Terraform Plan

on:
  workflow_dispatch:
  push:
    branches:
      - infra
      - infra-config

  pull_request:
    branches:
      - infra
      - infra-config


jobs:
  terraform-dev:
    name: Terraform Dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials (dev)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN_DEV }}
          aws-region:            ${{ secrets.AWS_REGION_DEV }}

      - name: Test AWS credentials
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init -backend-config=backend-dev.tfbackend


      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -var-file=dev.tfvars

      - name: Terraform Apply
        id: terraform-apply
        run: |
          set +e
          terraform apply -auto-approve -input=false -var-file=dev.tfvars
          status=$?
          if [ $status -ne 0 ]; then
            echo "::warning ::Terraform apply falló con código $status"
            if [ -f errored.tfstate ]; then
              echo "::notice ::Intentando push del estado..."
              terraform state push errored.tfstate
            else
              echo "::error ::No se encontró errored.tfstate para recuperar el estado"
            fi
            exit $status
          fi


      - name: Crear log groups para ECS (dev)
        run: |
          aws logs describe-log-groups --log-group-name-prefix /ecs/vote | grep "/ecs/vote" || aws logs create-log-group --log-group-name /ecs/vote
          aws logs describe-log-groups --log-group-name-prefix /ecs/result | grep "/ecs/result" || aws logs create-log-group --log-group-name /ecs/result
          aws logs describe-log-groups --log-group-name-prefix /ecs/worker | grep "/ecs/worker" || aws logs create-log-group --log-group-name /ecs/worker
          aws logs describe-log-groups --log-group-name-prefix /ecs/seed-data | grep "/ecs/seed-data" || aws logs create-log-group --log-group-name /ecs/seed-data

  terraform-prod:
    name: Terraform Prod
    needs: terraform-dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials (prod)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN_PROD }}
          aws-region:            ${{ secrets.AWS_REGION_PROD }}

      - name: Test AWS credentials
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init -backend-config=backend-prod.tfbackend


      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -var-file=prod.tfvars

      - name: Terraform Apply
        id: terraform-apply
        run: |
          set +e
          terraform apply -auto-approve -input=false -var-file=prod.tfvars
          status=$?
          if [ $status -ne 0 ]; then
            echo "::warning ::Terraform apply falló con código $status"
            if [ -f errored.tfstate ]; then
              echo "::notice ::Intentando push del estado..."
              terraform state push errored.tfstate
            else
              echo "::error ::No se encontró errored.tfstate para recuperar el estado"
            fi
            exit $status
          fi


      - name: Crear log groups para ECS (prod)
        run: |
          aws logs describe-log-groups --log-group-name-prefix /ecs/vote | grep "/ecs/vote" || aws logs create-log-group --log-group-name /ecs/vote
          aws logs describe-log-groups --log-group-name-prefix /ecs/result | grep "/ecs/result" || aws logs create-log-group --log-group-name /ecs/result
          aws logs describe-log-groups --log-group-name-prefix /ecs/worker | grep "/ecs/worker" || aws logs create-log-group --log-group-name /ecs/worker
          aws logs describe-log-groups --log-group-name-prefix /ecs/seed-data | grep "/ecs/seed-data" || aws logs create-log-group --log-group-name /ecs/seed-data
